-- Benchmark schema. Idempotent.

BEGIN;

CREATE EXTENSION IF NOT EXISTS pg_stat_statements;

-- ---------------------------------------------------------------------------
-- Reference data
-- ---------------------------------------------------------------------------

CREATE TABLE categories (
    id   integer PRIMARY KEY,
    name text    NOT NULL,
    slug text    NOT NULL UNIQUE
);

CREATE TABLE customers (
    id         bigint  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email      text    NOT NULL UNIQUE,
    full_name  text    NOT NULL,
    country    char(2) NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);

-- The read workload's target. Wide enough (~400 bytes) that serialization is
-- a real cost, narrow enough that the whole table sits in shared_buffers and
-- the benchmark measures the framework's driver + serializer, not disk.
CREATE TABLE products (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku         text   NOT NULL UNIQUE,
    name        text   NOT NULL,
    description text   NOT NULL,
    category_id integer NOT NULL REFERENCES categories(id),
    price_cents integer NOT NULL CHECK (price_cents >= 0),
    -- Stock is decremented by the write workload; that is what makes it a
    -- genuine read-modify-write under contention rather than an append-only
    -- insert.
    stock       integer NOT NULL CHECK (stock >= 0),
    active      boolean NOT NULL DEFAULT true,
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now()
);

-- Serves the dashboard's per-category aggregate. Without it that workload
-- would measure a sequential scan, not the framework.
CREATE INDEX products_category_active_idx
    ON products (category_id, active)
    INCLUDE (price_cents);

-- ---------------------------------------------------------------------------
-- Transactional write workload
-- ---------------------------------------------------------------------------

CREATE TYPE order_status AS ENUM ('pending', 'paid', 'shipped', 'cancelled');

CREATE TABLE orders (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id     bigint NOT NULL REFERENCES customers(id),
    status          order_status NOT NULL DEFAULT 'pending',
    total_cents     integer NOT NULL CHECK (total_cents >= 0),
    -- Idempotency is part of the API contract; every framework must
    -- implement it and the cost is measured uniformly.
    idempotency_key uuid NOT NULL UNIQUE,
    created_at      timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX orders_customer_created_idx ON orders (customer_id, created_at DESC);
CREATE INDEX orders_created_idx         ON orders (created_at DESC);

CREATE TABLE order_items (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id         bigint NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    product_id       bigint NOT NULL REFERENCES products(id),
    quantity         integer NOT NULL CHECK (quantity > 0),
    unit_price_cents integer NOT NULL CHECK (unit_price_cents >= 0)
);

CREATE INDEX order_items_order_idx   ON order_items (order_id);
CREATE INDEX order_items_product_idx ON order_items (product_id);

-- A ledger row per order makes the write workload span three tables, which
-- is the point: single-table inserts do not exercise transaction handling.
CREATE TABLE inventory_ledger (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id bigint NOT NULL REFERENCES products(id),
    order_id   bigint NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    delta      integer NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX inventory_ledger_product_idx ON inventory_ledger (product_id, created_at DESC);

-- Reference data: fixed category set so every trial sees the same distribution.
TRUNCATE categories CASCADE;
INSERT INTO categories (id, name, slug) VALUES
    (1,'Electronics','electronics'),(2,'Books','books'),
    (3,'Clothing','clothing'),(4,'Home','home'),
    (5,'Toys','toys'),(6,'Grocery','grocery'),
    (7,'Sports','sports'),(8,'Beauty','beauty'),
    (9,'Tools','tools'),(10,'Garden','garden'),
    (11,'Automotive','automotive'),(12,'Music','music'),
    (13,'Movies','movies'),(14,'Office','office'),
    (15,'Pet','pet'),(16,'Health','health'),
    (17,'Outdoors','outdoors'),(18,'Industrial','industrial'),
    (19,'Jewelry','jewelry'),(20,'Baby','baby'),
    (21,'Software','software'),(22,'Gifts','gifts'),
    (23,'Stationery','stationery'),(24,'Art','art'),
    (25,'Crafts','crafts');

COMMIT;
